### ISSUE TITLE
Boot failed during install

### ISSUE THREAD

**Issue by jesperweber** [ArnoldV/Our.Umbraco.GMaps#98] opened 2022-03-31 09:11 UTC
We have an Umbraco 8.17.1 site running and installed the Our.Umbraco.GMaps Nuget package and every thing works fines.

However if we delete the database and clears the values for Umbraco.Core.ConfigurationStatus and umbracoDbDSN in the web.config to enforce a new Umbraco install we get a boot failed.

If we remove the Nuget package again the install works fine.

![image](https://user-images.githubusercontent.com/2575817/161019413-e7a26cb8-5bfe-4836-856c-9dd7729352d3.png)

![image](https://user-images.githubusercontent.com/2575817/161019438-921ad524-3cd8-4211-832a-333f13d7ed7a.png)

**Comment by ronaldbarendse** [comment] 2022-03-31 12:30
I see the problem is caused by the fact that the `SingleMapPropertyValueConverter` is automatically discovered, but the constructor requires the `GoogleMapsConfig` to be registered in DI. This is done in a composer, but that only runs when Umbraco's runtime level is `RuntimeLevel.Run`:

https://github.com/ArnoldV/Our.Umbraco.GMaps/blob/ca7663a570ae2ebeade2e4f2eaee174f804782a7/Our.Umbraco.GMaps.Core/Composing/Composer.cs#L17-L18

Hence the unresolved dependency error you're seeing. This should be easily fixed by changing the above to use `RuntimeLevel.Boot` instead. You can also work-around this issue by registering the `GoogleMapsConfig` type yourself (although I'm not sure what happens if it gets registered twice, I haven't tested this in any way):

```c#
[RuntimeLevel(MinLevel = RuntimeLevel.Boot)]
public class GoogleMapsConfigComposer : IComposer
{
    public void Compose(Composition composition)
    {
        composition.Register<GoogleMapsConfig>();
    }
}
```

**Comment by jesperweber** [comment] 2022-03-31 14:03
Thanks @ronaldbarendse, from a quick test it seems to work by registering the `GoogleMapConfig` at boot time. The Umbraco install starts and the map works.

Of course it would be nice with a permanent fix in the Our.Umbraco.GMaps package.

**Comment by Fjellvang** [comment] 2022-04-06 06:23
I had the same issue, so i made a PR here: https://github.com/ArnoldV/Our.Umbraco.GMaps/pull/100

**Comment by robertjf** [comment] 2022-05-06 17:53
thanks for your PR @Fjellvang - it's finally been incorporated!

**Closed by robertjf** 2022-05-06 17:53 UTC
