### ISSUE TITLE
Deprecated Google Maps Library

### ISSUE THREAD

**Issue by abdulhade** [ArnoldV/Our.Umbraco.GMaps#176] opened 2024-09-10 08:29 UTC
Dear owner,

I hope you are doing well.

Could you help me please?

The warning bellow does my map not showing:

js?key=XXXXX&callback=XXXX.locationMap:200 As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. At this time, google.maps.Marker is not scheduled to be discontinued, but google.maps.marker.AdvancedMarkerElement is recommended over google.maps.Marker. While google.maps.Marker will continue to receive bug fixes for any major regressions, existing bugs in google.maps.Marker will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide.

**Comment by robertjf** [comment] 2024-09-10 08:43
@abdulhade is this on your front end implementation or in the Umbraco BackOffice?

**Comment by abdulhade** [comment] 2024-09-10 08:45
Hi @robertjf it is implemented on my frontend.

**Comment by abdulhade** [comment] 2024-09-10 09:10
Sorry @robertjf . I don't understand why I need to review. It is your library whose responsable to render the google maps on my frontend. 

Maybe, I didn't explain myself correctly.

I installed your plugin in my backoffice umbraco, I created datatypes that is using your Property Editr. A

And then I implement this property on my documentType that renders on my frontend.

**Comment by abdulhade** [comment] 2024-09-10 16:07
Hi @robertjf , I checked this error on BackOffice now and it is showing the same error.

**Comment by robertjf** [comment] 2024-09-10 17:26
ok, can you please add some details to the error in the BackOffice - Dev Console logs, errors, etc.

**Comment by abdulhade** [comment] 2024-09-11 10:42
Hi, @robertjf , 

I'm sorry, what kind of detail do you need? It is the same error. Do you need a print screen, like this?
![image](https://github.com/user-attachments/assets/55d58ed4-e9d7-4c8c-b3fa-f46522d2c554)

js?key=XXXXX&libraries=places&callback=googleMapsInitialized:671 As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. At this time, google.maps.Marker is not scheduled to be discontinued, but google.maps.marker.AdvancedMarkerElement is recommended over google.maps.Marker. While google.maps.Marker will continue to receive bug fixes for any major regressions, existing bugs in google.maps.Marker will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide.

**Comment by abdulhade** [comment] 2024-09-12 13:24
Hi @robertjf 

Version of Our.Umbraco.GMap:

- 1.2.0 with Umbraco 8.18.14;
- 3.0.2 with Umbraco 13.4.1.

About the Google Maps API Key, I did it because I can't show you this information.

Best regards,
Abdul Abbas

**Comment by JasonElkin** [comment] 2024-09-25 09:42
I've just come across this same warning.

It _is_ an issue in the Backoffice, here's a screengrab from an Umbraco v13.5 site, with GMaps v3.0.2 installed:
![image](https://github.com/user-attachments/assets/89c7662a-b31d-4494-b821-406c606ae9fa)

Everything still works fine, and it looks like there's no plan to remove the feature just yet - but it has been flagged by one of our clients following a regression test.

**Comment by robertjf** [comment] 2024-12-15 22:37
This has now been resolved with the latest release

**Closed by robertjf** 2024-12-15 22:37 UTC
